name = "Seven Oaks 3"
author = "Koruudo"
version = "3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a0fe9326246cb85a76e0d5381e0af577d63ab04a32f9432ac8e66b3efb8f495"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
