name = "Seven Oaks 3"
author = "Koruudo"
version = "3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33bd147b42a50df52b4d94c310787ddb5b8fdff35c9a8df4c862b0d16e6502e3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
pinned-game-versions = []
