name = "Seven Oaks 3"
author = "Koruudo"
version = "3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5913739459f73228cce615eee6c0492a851ecf40dc0dc81b416ea614bc48380a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
